### ISSUE TITLE
[Backend] The download script cannot grab the applicant table data

### ISSUE THREAD

**Issue by ShutoAraki** [ShutoAraki/gbfdx#2]
Somehow the PDF downloader stopped working.

The error comes from the logic where it grabs rows from the table:

L78 on `index.ts`: `const tableRows = await page.$$('#lstApplicants tbody tr');`

This results in an empty table. It can find the table and `tbody` element, but not `tr` for some reason...
```
$ node -v
v14.8.0

$ npm -v
6.14.7
```
The same issue happens with Lambda too, which uses Node.js 12.x.
It doesn't seems like syutsugan.net changed their HTML structure. Nothing was modified about puppeteer... So I'm not sure what the root cause might be 🤷

**Comment by ShutoAraki** [comment]
What do you think? @jul21pf

**Comment by ShutoAraki** [comment]
![image](https://user-images.githubusercontent.com/24555667/126033998-cc38a734-67d1-490c-89fb-c5744321cc03.png)

**Comment by ShutoAraki** [comment]
When I execute the selector `document.querySelectorAll('#lstApplicants tbody tr')` from the Chrome console , it works fine.
But it doesn't work from puppeteer... I give up now lol

**Comment by jul21pf** [comment]
😮

It actually worked for me... Just in case, did you remember to pass the setting argument for `setFilter` as follows?
`{"year": 2022}`

![image](https://user-images.githubusercontent.com/58774385/126035509-f6414fd2-b340-4fe6-978b-c4a48e18cb14.png)

@ShutoAraki

**Comment by ShutoAraki** [comment]
THANK YOU!! That's it I had it 2021.
Sorry it wasn't the code lol
